myproject/core/urls.py
from django.urls import path

from myproject.core import views as v

app_name = 'core'


urlpatterns = [
    path('', v.home, name='home'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from myproject.core.forms import LoginForm

urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path(
        'login/',
        LoginView.as_view(
            template_name='core/auth.html', authentication_form=LoginForm
        ),
        name='authenticate'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    cpf = models.CharField(max_length=14, unique=True)

    def __str__(self):
        return str(self.user)

myproject/core/forms.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.fields['username'].label = 'CPF'
        self.fields['username'].verbose_name = 'CPF'

myproject/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/index.html')

myproject/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <!-- <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico"> -->
  <title>{% block title %} Custom Login {% endblock title %}</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    body {
      margin-top: 60px;
    }
  </style>

  {% block css %}{% endblock css %}

  </body>
</head>
<body>

  {% include "includes/nav.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/core/auth.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Auth{% endblock title %}

{% block content %}

{% for message in messages %}
  {% if 'success' in message.tags %}
  <p class="alert alert-success" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
  {% else %}
  <p class="alert alert-danger" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
  {% endif %}
{% endfor %}

<form class="form-horizontal" action="." method="POST">
    {% csrf_token %}
    {{ form.non_fields_errors }}
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.username.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.username|attr:"class:form-control" }} {{ form.cpf.errors }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2 col-lg-2">
            {{ form.password.label }}
        </label>
        <div class="col-sm-4 col-lg-4">
            {{ form.password|attr:"class:form-control" }} {{ form.password.errors }}
        </div>
    </div>

    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </div>
</form>

{% endblock content %}

{% block js %}
  <script>
    // Close alert after 2 seconds
    window.setTimeout(function() {
      $('.alert').fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 2000);
  </script>
{% endblock js %}

myproject/core/templates/core/index.html
{% extends "base.html" %}

{% block content %}

{% for message in messages %}
  {% if 'success' in message.tags %}
  <p class="alert alert-success" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
  {% else %}
  <p class="alert alert-danger" role="alert"><span style="font-weight:bold">{{ message }}</span></p>
  {% endif %}
{% endfor %}

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Bem-vindo!</h1>
    <p>Exemplo de login com CPF.</p>
    {% if user.is_authenticated %}
      <p>Seu login é {{ request.user }}</p>
    {% endif %}
  </div>
</div>

{% endblock content %}

myproject/core/templates/includes/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'core:home' %}">Custom Login</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authenticate' %}">Login com CPF</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
        {% endif %}
    </div>
</nav>